name: Hello World
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Print Hello World
        run: 'echo "Hello World"'

      - name: Checkout code
        uses: actions/checkout@v4 

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
          use-cache: false

      - name: Run test
        run: |
         ls
         zig run ./foo.zig
